DJANGO_SECRET_KEY: "abc"
DEBUG: True

ALLOWED_HOSTS: ['*']

Access-Control-Allow-Origin: *
MIN_BLOCKS_FOR_SCANNER: 8
SCANNER_SLEEP_IN_SECONDS: 60
CONTRACT_ADDRESS: "TPKJzp3QcRbe9vuLmhQCZChZKWkXQjjNhs"
START_BLOCK_FOR_SCANNER: 21007565
ENDPOINT: 'https://api.shasta.trongrid.io'